default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud config set project $PROJECT_ID
    - export GOOGLE_CLOUD_CREDENTIALS=$(echo $BASE64_GOOGLE_CLOUD_CREDENTIALS | base64 -d)
    - echo $GOOGLE_CLOUD_CREDENTIALS > service-account-key.json
    - gcloud auth activate-service-account --key-file service-account-key.json
    - gcloud auth configure-docker

build:
  stage: build
  script:
    - gcloud builds submit --tag gcr.io/$PROJECT_ID/$PARTNER_SERVICE_ID
  only:
    - feature-restaurant_details

deploy:
  stage: deploy
  script:
    - gcloud run deploy $PARTNER_SERVICE_ID --image gcr.io/$PROJECT_ID/$PARTNER_SERVICE_ID --region=us-central1 --platform managed --allow-unauthenticated
