steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-east1-docker.pkg.dev/serverless-402501/book-a-bite-admin-app/book-a-bite-admin-app"
      - "./AdminApp/Frontend"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-east1-docker.pkg.dev/serverless-402501/book-a-bite-admin-app/book-a-bite-admin-app"
  - name: "google/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud auth activate-service-account --key-file=CustomerApp/Frontend/keys/serverless-402501-c5f01ca20843.json
        gcloud run deploy book-a-bite-admin-app \
          --image=us-east1-docker.pkg.dev/serverless-402501/book-a-bite-admin-app/book-a-bite-admin-app \
          --region=us-east1 \
          --platform=managed \
          --allow-unauthenticated \
          --memory=2Gi \
          --cpu=2
images:
  - "us-east1-docker.pkg.dev/serverless-402501/book-a-bite-admin-app/book-a-bite-admin-app"
