steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-east1-docker.pkg.dev/serverless-402501/book-a-bite-customer-app/book-a-bite"
      - "./CustomerApp/Frontend"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-east1-docker.pkg.dev/serverless-402501/book-a-bite-customer-app/book-a-bite"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "book-a-bite",
        "--image",
        "us-east1-docker.pkg.dev/serverless-402501/book-a-bite-customer-app/book-a-bite",
        "--region",
        "us-east1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images:
  - "us-east1-docker.pkg.dev/serverless-402501/book-a-bite-customer-app/book-a-bite"
